/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import clase.Ncomplejo;
import javax.swing.JOptionPane;

/**
 *
 * @author adalberto
 */
public class principall extends javax.swing.JFrame {

    /**
     * Creates new form principall
     */
    public principall() {
        initComponents();
        cmdCalcular.setEnabled(true);
        cmdSalir.setEnabled(false);
        cmdLimpiar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtReal1 = new javax.swing.JTextField();
        txtImaginario1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtReal2 = new javax.swing.JTextField();
        txtImaginario2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtReal3 = new javax.swing.JTextField();
        txtImaginario3 = new javax.swing.JTextField();
        cmbOperacion = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        cmdCalcular = new javax.swing.JButton();
        cmdSalir = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        cmdLimpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 204));
        jLabel1.setText("OPERACIONES CON NUMEROS COMPLEJOS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel2.setText("P. Real:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel3.setText("P. Imaginaria:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, -1, -1));

        txtReal1.setBackground(new java.awt.Color(153, 153, 153));
        txtReal1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        txtReal1.setForeground(new java.awt.Color(0, 255, 255));
        txtReal1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtReal1KeyTyped(evt);
            }
        });
        jPanel1.add(txtReal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 50, -1));

        txtImaginario1.setBackground(new java.awt.Color(153, 153, 153));
        txtImaginario1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        txtImaginario1.setForeground(new java.awt.Color(0, 255, 255));
        txtImaginario1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtImaginario1KeyTyped(evt);
            }
        });
        jPanel1.add(txtImaginario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 50, -1));

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel4.setText("P. Real:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 50, -1, -1));

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel5.setText("P. Imaginaria:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 50, -1, -1));

        txtReal2.setBackground(new java.awt.Color(153, 153, 153));
        txtReal2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        txtReal2.setForeground(new java.awt.Color(0, 255, 255));
        txtReal2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtReal2KeyTyped(evt);
            }
        });
        jPanel1.add(txtReal2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, 50, -1));

        txtImaginario2.setBackground(new java.awt.Color(153, 153, 153));
        txtImaginario2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        txtImaginario2.setForeground(new java.awt.Color(0, 255, 255));
        txtImaginario2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtImaginario2KeyTyped(evt);
            }
        });
        jPanel1.add(txtImaginario2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 70, 50, -1));

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel6.setText("P. Real:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, -1, -1));

        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel7.setText("P. Imaginaria:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, -1, -1));

        txtReal3.setEditable(false);
        txtReal3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        txtReal3.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(txtReal3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 50, -1));

        txtImaginario3.setEditable(false);
        txtImaginario3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        txtImaginario3.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(txtImaginario3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, 50, -1));

        cmbOperacion.setBackground(new java.awt.Color(204, 255, 255));
        cmbOperacion.setFont(new java.awt.Font("Trebuchet MS", 1, 13)); // NOI18N
        cmbOperacion.setForeground(new java.awt.Color(102, 102, 255));
        cmbOperacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Suma", "Resta", "Multiplicación", "División" }));
        jPanel1.add(cmbOperacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel8.setText("Resultado");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 100, 20));

        cmdCalcular.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cmdCalcular.setForeground(new java.awt.Color(102, 102, 255));
        cmdCalcular.setText("CALCULAR");
        cmdCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCalcularActionPerformed(evt);
            }
        });
        jPanel1.add(cmdCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, -1, -1));

        cmdSalir.setBackground(new java.awt.Color(0, 0, 0));
        cmdSalir.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cmdSalir.setForeground(new java.awt.Color(102, 102, 255));
        cmdSalir.setText("Salir");
        cmdSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdSalirActionPerformed(evt);
            }
        });
        jPanel1.add(cmdSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 220, -1, -1));

        jLabel9.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel9.setText("i");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, -1, -1));

        jLabel10.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel10.setText("i");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, 30, 30));

        jLabel11.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel11.setText("i");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 70, 20, 30));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel12.setText("+");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, 20, 20));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel13.setText("+");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 20, 20));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel14.setText("+");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 70, 20, 20));

        cmdLimpiar.setBackground(new java.awt.Color(153, 153, 153));
        cmdLimpiar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cmdLimpiar.setForeground(new java.awt.Color(0, 255, 255));
        cmdLimpiar.setText("LIMPIAR");
        cmdLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdLimpiarActionPerformed(evt);
            }
        });
        jPanel1.add(cmdLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 653, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 357, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtReal1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtReal1KeyTyped
        char c=evt.getKeyChar();
        if(!Character.isDigit(c)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtReal1KeyTyped

    private void txtImaginario1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtImaginario1KeyTyped
        char c=evt.getKeyChar();
        if(!Character.isDigit(c)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtImaginario1KeyTyped

    private void txtReal2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtReal2KeyTyped
        char c=evt.getKeyChar();
        if(!Character.isDigit(c)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtReal2KeyTyped

    private void txtImaginario2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtImaginario2KeyTyped
        char c=evt.getKeyChar();
        if(!Character.isDigit(c)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtImaginario2KeyTyped

    private void cmdCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCalcularActionPerformed
        int op,r1,r2,imaginario1,imaginario2;
        Ncomplejo f = null,f1,f2;

        if(txtReal1.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "Digite la Parte Real en el primer número complejo", "Error", JOptionPane.ERROR_MESSAGE);
            txtReal1.requestFocusInWindow();
        }else if(txtReal2.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "Digite la Parte Real en el segundo número complejo", "Error", JOptionPane.ERROR_MESSAGE);
            txtReal2.requestFocusInWindow();
        }else if(txtImaginario1.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "Digite la Parte Imaginaria en el primer número complejo", "Error", JOptionPane.ERROR_MESSAGE);
            txtImaginario1.requestFocusInWindow();
        }else if(txtImaginario2.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "Digite la Parte Imaginaria en el segundo número complejo", "Error", JOptionPane.ERROR_MESSAGE);
            txtImaginario2.requestFocusInWindow();
        }else{

            op=cmbOperacion.getSelectedIndex();
            r1=Integer.parseInt(txtReal1.getText());
            r2=Integer.parseInt(txtReal2.getText());
            imaginario1=Integer.parseInt(txtImaginario1.getText());
            imaginario2=Integer.parseInt(txtImaginario2.getText());

            f1=new Ncomplejo(r1,imaginario1);
            f2=new Ncomplejo(r2,imaginario2);

            switch(op){
                case 0:
                f=f1.Sumar(f2);
                break;

                case 1:
                f=f1.Restar(f2);
                break;

                case 2:
                f=f1.Multiplicar(f2);
                break;

                case 3:
                f=f1.Dividir(f2);
                break;
            }
            txtReal3.setText(""+f.getReal());
            txtImaginario3.setText(""+f.getImaginario());
            cmdCalcular.setEnabled(false);
        cmdSalir.setEnabled(true);
        cmdLimpiar.setEnabled(true);
        }
    }//GEN-LAST:event_cmdCalcularActionPerformed

    private void cmdSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_cmdSalirActionPerformed

    private void cmdLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdLimpiarActionPerformed
        txtImaginario1.setText("");
        txtImaginario2.setText("");
        txtImaginario3.setText("");
        txtReal1.setText("");
        txtReal2.setText("");
        txtReal3.setText("");
        txtImaginario1.requestFocusInWindow();
        cmdCalcular.setEnabled(true);
        cmdSalir.setEnabled(true);
        cmdLimpiar.setEnabled(true);
    }//GEN-LAST:event_cmdLimpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(principall.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(principall.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(principall.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principall.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new principall().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbOperacion;
    private javax.swing.JButton cmdCalcular;
    private javax.swing.JButton cmdLimpiar;
    private javax.swing.JButton cmdSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtImaginario1;
    private javax.swing.JTextField txtImaginario2;
    private javax.swing.JTextField txtImaginario3;
    private javax.swing.JTextField txtReal1;
    private javax.swing.JTextField txtReal2;
    private javax.swing.JTextField txtReal3;
    // End of variables declaration//GEN-END:variables
}
